#!/usr/bin/env python3
"""Render a task.yaml as submission.md - one section per authoring-form field.

    python3 tools/render_submission.py tasks/<slug>/task.yaml
    python3 tools/render_submission.py --all --check

`submission.md` is a derived file: keep the prose in `task.yaml` so there is
exactly one copy of it, and regenerate. Each section carries its character count
against the form's limit, so you can see at a glance which fields are near the
cap while pasting.

`--check` regenerates in memory and fails if the file on disk is stale, which is
what CI (and the pre-push habit) should run.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent

BANNER = (
    "<!-- Generated by tools/render_submission.py from task.yaml. "
    "Edit task.yaml, not this file. -->"
)

# (form label, yaml key, limit or None)
SECTIONS = [
    ("Task identity", None, None),
    ("Title", "title", None),
    ("Working slug", "working_slug", 80),
    ("Collection family", "collection_family", None),
    ("Task family", "task_family", None),
    ("Verifier family", "verifier_family", None),
    ("What the task is", None, None),
    ("Objective", "objective", 20_000),
    ("Motivation", "motivation", 10_000),
    ("Environment summary", "environment_summary", 20_000),
    ("Difficulty & effort", None, None),
    ("Difficulty explanation", "difficulty_explanation", 20_000),
    ("Expert time estimate (hours)", "expert_time_estimate_hours", None),
    ("Oracle & verification", None, None),
    ("Oracle strategy", "oracle_strategy", 20_000),
    ("Verification strategy", "verification_strategy", 20_000),
    ("Binary success condition", "binary_success_condition", 10_000),
    ("Partial score strategy", "partial_score_strategy", 10_000),
    ("Anticipated exploits", "anticipated_exploits", 20_000),
]


def render(doc: dict) -> str:
    lines = [BANNER, "", f"# {doc.get('title', '(untitled)')}", ""]

    for label, key, limit in SECTIONS:
        if key is None:
            lines += [f"## {label}", ""]
            continue

        value = doc.get(key)
        if value is None or value == "":
            lines += [f"### {label}", "", "_(choose in the form)_", ""]
            continue

        text = str(value).rstrip("\n")
        if limit is not None:
            lines += [f"### {label}", "", f"`{len(text)} / {limit} chars`", ""]
        else:
            lines += [f"### {label}", ""]

        if "\n" in text:
            lines += [text, ""]
        else:
            lines += [text, ""]

    resources = doc.get("resources") or {}
    lines += [
        "## Resource request",
        "",
        "| field | value |",
        "| --- | --- |",
        f"| CPU (millis) | {resources.get('cpu_millis', '')} |",
        f"| Memory (MB) | {resources.get('memory_mb', '')} |",
        f"| Storage (MB) | {resources.get('storage_mb', '')} |",
        f"| GPU count | {resources.get('gpu_count', '')} |",
        f"| Agent timeout (s) | {resources.get('agent_timeout_s', '')} |",
        f"| Verifier timeout (s) | {resources.get('verifier_timeout_s', '')} |",
        "",
    ]

    network = doc.get("network") or {}
    justification = (network.get("justification") or "").rstrip("\n")
    lines += [
        "## Network requirements",
        "",
        f"**Mode:** {network.get('mode', '')}",
        "",
        "**Justification:** " + (justification or "_(not required for mode `none`)_"),
        "",
    ]

    notes = (doc.get("notes") or "").rstrip("\n")
    if notes:
        lines += ["## Authoring notes", "", "_Not a form field._", "", notes, ""]

    return "\n".join(lines).rstrip("\n") + "\n"


def process(path: Path, check: bool) -> bool:
    doc = yaml.safe_load(path.read_text())
    target = path.parent / "submission.md"
    rendered = render(doc)
    rel = target.relative_to(REPO) if target.is_relative_to(REPO) else target

    if check:
        current = target.read_text() if target.exists() else ""
        if current == rendered:
            print(f"OK    {rel}")
            return True
        print(f"STALE {rel} - run tools/render_submission.py")
        return False

    target.write_text(rendered)
    print(f"wrote {rel} ({len(rendered)} bytes)")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    paths = list(args.paths)
    if args.all or not paths:
        paths = sorted((REPO / "tasks").glob("*/task.yaml"))
    if not paths:
        print("no task.yaml found")
        return 1

    return 0 if all(process(p, args.check) for p in paths) else 1


if __name__ == "__main__":
    sys.exit(main())
